### PR TITLE
[Documentation] Add Contribution Guide to README

### PR DESCRIPTION
**Pull request by MalHus**
**Purpose**
Add a section to the `README` that outlines the steps for contributing to the repository. This will help new contributors understand how to fork, clone, make changes and open a pull request.

**Changes**
- Add proposed guide 
- Add a note under the guide explaining who the audience of the guide is

Additional Info
- #7 
- **Question:** I was making a minor change to these notes when I noticed that they both refer to `template.html` which is a file that doesn't seem to exist in the repo. Would you know if its still there and I accidentally missed it or if its deletion was intentional? 
image

### CODE REVIEW

**Comment by MalHus** [comment]
This is not neccessary but we can also add that these need to be done if contributions are made:
- Create a Issue with the title hvaing a tag like ([Bug], [Feature]) 
- Create a PR. In the title copy the corressponding Issue title and in the description follow format: Purpose, Changes, Additional Info (link to Issue here)

**Review by helenaglow — APPROVED** [review]
Amazing Malaikah! I know this documentation will be helpful to have in the long run.

**Comment by MalHus** [comment]
Thanks Helena!

Just wondering if we have any insight on this?
> * **Question:** I was making a minor change to these notes when I noticed that they both refer to `template.html` which is a file that doesn't seem to exist in the repo. Would you know if its still there and I accidentally missed it or if its deletion was intentional?

And if we would still like to add this?
> This is not neccessary but we can also add that these need to be done if contributions are made:
> 
> * Create a Issue with the title having a tag (ex: [Bug], [Feature] etc.)
> * Create a PR. In the title copy the corressponding Issue title and in the description follow **format**: Purpose, Changes, Additional Info (link to Issue here)
> * Close the associated Issue

**Comment by MalHus** [comment]
Made new issue to address the remaining changes: https://github.com/WISE-UofT/wise-main/issues/24

**Pull request merged**
