### PR TITLE
[Enhancement] Add Informational Banner to Pages that Cannot be Updated 

### PR DESCRIPTION
**Pull request by MalHus**
**Purpose**
- Add a temporary banner on pages that will be updated in September 2024

**Changes**
- Add banner to WISE EVENTS, INITIATIVES > COMMUNITY, HIGHSCHOOL and INDUSTRY

https://github.com/user-attachments/assets/c9771769-fe36-4730-a705-f286ab0aacf1

**Additional Info** 
- #10

### CODE REVIEW

**Comment by MalHus** [comment]
Please let me know if there are other pages that need this banner.

**Comment by helenaglow** [comment]
BEAUTIFULLL!!! Would you just mind adding a little padding above and below? maybe like 2px more. Also questions: How does it look when you make the browser smaller?

**Comment by MalHus** [comment]
I have added 2px around the banner. This involved increasing `margin-bottom` of the `info-banner`  by 2px and since adding a `margin-top` to the class was causing the following glitch, the only way to add spacing/padding was to change the `spacer-color` class to have a greater height (+2vh). This class, `spacer-color` is being used in `events.html` and `conference.html` and I have ensured this additional spacing does not impact 'conference.html`. 

image

https://github.com/user-attachments/assets/bcd1cec9-bbb9-4425-8200-cf58b60af9a4

**Comment by MalHus** [comment]
Should the banner be added to https://wise.skule.ca/sponsors.html as well since the banner here is outdated?
image

**Review by helenaglow — CHANGES_REQUESTED** [review]
Good catch on the sponsorship! Could we change that to be 2024-2025 school year instead in this PR as well?

Also, a little nitpicky, but could we have a less cursive i for the information circle? Otherwise AMAZING THANK YOU

**Comment by MalHus** [comment]
Yes! 

_So these are the tasks, please correct me if I missed anything!_

1. Add banner to sponsorship page
2. Update date on sponsorship banner
3. Update icon used for info banner - just looking around, it seems like the repo is using [Font Awesome](https://fontawesome.com/search?q=info&o=r) and [Ionicons](https://ionic.io/ionicons). Let me know which one we'd like to use!

**Comment by helenaglow** [comment]
Yes exactly! In that case, I think this icon from https://ionic.io/ionicons would be good Screenshot 2024-08-19 at 8 04 12 PM

**Comment by MalHus** [comment]
How is this? @helenaglow 
image

**Comment by helenaglow** [comment]
Is there a way to change the weight? For example making the stroke thinner?

**Comment by MalHus** [comment]
> Is there a way to change the weight? For example making the stroke thinner? @MalHus

Yes, however I am unable to make changes on this branch anymore (not sure what happened) so I will address this in another issue.

**Pull request merged**
