### PR TITLE
[Bug] Fix Padding around WISE Logo in Nav Bar 

### PR DESCRIPTION
**Pull request by MalHus**
**Purpose**
- The WISE logo in the navigation bar has uneven padding, when landing on any page
- This issue is resolved when the page is scrolled, causing all the text in the navbar to readjust and the padding around the logo to be fixed

**Changes**
- This PR ensures that the WISE logo has even padding on all sides when the page initially loads, without requiring a scroll to correct the issue

_Before:_
image
_After:_
image

**Additional Info**
- #8

### CODE REVIEW

**Comment by helenaglow** [comment]
Screenshot 2024-08-10 at 4 06 34 PM
Could you move it all to be centered? When you scroll down on the website, it become beautiful but its not consistent when the website first loads

**Comment by MalHus** [comment]
I agree! 

The movement was caused by the following style:
`#header.header-scrolled #topbar,
#header.header-pages #topbar {
    display: none;
}`

To ensure the positioning of the nav bar's content is consistent throughout the scrolling process, the `display: none` style of `#header.header-scrolled #topbar` and `#header.header-pages #topbar` was deleted. Since there is no longer a transition required, the `transition: all 0.5s` from `#header` was deleted. Lastly, to ensure the padding remains same before and after scrolling, the `padding` for `#header` was changed to match the `padding` of  `#header.header-scrolled, #header.header-pages`.

The narv bar content is not centered since I personally think it looks good. However, if you would like me to center the content, let me know as its a simple fix: 

https://github.com/user-attachments/assets/3d9640c6-b3de-4d53-bbc7-400c90224892

**Comment by MalHus** [comment]
Apologies, this caused another issue. I am investigating 🔎


https://github.com/user-attachments/assets/7d0020f9-b0ea-4110-a308-a26d5d8d9498

**Comment by helenaglow** [comment]
Good catch on the bug omg!

**Review by helenaglow — APPROVED** [review]
Perfect! Thank you Malaikah for figuring this out.

**Pull request merged**
